name: .talk_to_pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - numpy
    - openai
    - requests
    - sqlalchemy
    - pdfminer.six
    - streamlit-lottie
    - pydrive
    - oauth2client
